pipeline {
	agent any
	stages {
		stage('Copy artifact') {
			steps {
				copyArtifacts filter: 'Class2', fingerprintArtifacts: true, projectName: 'Class2', selector: lastSuccessful(), target: 'docker'
			}
		}
		stage('Docker build and upload to ') {
			steps {
				script {
					docker.withRegistry('', 'dockerhub') {					
						def customImage = docker.build("jonathanhar/simple-go-server:latest", "./docker")
						customImage.push()						
					}
				}
			}
		}
	}
}