on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  get_to_dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: Let's go!
        uses: docker/build-push-action@v1
        with:
          username: jonathanhar
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: jonathanhar/simple-go-server
          tags: latest
  
